# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/fda/settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(281, 232)
        Settings.setStyleSheet("background-color: rgb(108, 136, 177);\n"
"color: rgb(255, 255, 255);")
        self.address = QtWidgets.QLabel(Settings)
        self.address.setGeometry(QtCore.QRect(10, 40, 61, 20))
        self.address.setAlignment(QtCore.Qt.AlignCenter)
        self.address.setObjectName("address")
        self.address_text = QtWidgets.QLineEdit(Settings)
        self.address_text.setGeometry(QtCore.QRect(100, 40, 151, 21))
        self.address_text.setObjectName("address_text")
        self.port_text = QtWidgets.QLineEdit(Settings)
        self.port_text.setGeometry(QtCore.QRect(100, 70, 151, 21))
        self.port_text.setObjectName("port_text")
        self.port = QtWidgets.QLabel(Settings)
        self.port.setGeometry(QtCore.QRect(10, 70, 31, 19))
        self.port.setAlignment(QtCore.Qt.AlignCenter)
        self.port.setObjectName("port")
        self.login = QtWidgets.QLabel(Settings)
        self.login.setGeometry(QtCore.QRect(10, 100, 40, 19))
        self.login.setAlignment(QtCore.Qt.AlignCenter)
        self.login.setObjectName("login")
        self.login_text = QtWidgets.QLineEdit(Settings)
        self.login_text.setGeometry(QtCore.QRect(100, 100, 151, 21))
        self.login_text.setObjectName("login_text")
        self.password = QtWidgets.QLabel(Settings)
        self.password.setGeometry(QtCore.QRect(10, 130, 71, 20))
        self.password.setAlignment(QtCore.Qt.AlignCenter)
        self.password.setObjectName("password")
        self.password_text = QtWidgets.QLineEdit(Settings)
        self.password_text.setGeometry(QtCore.QRect(100, 130, 151, 21))
        self.password_text.setObjectName("password_text")
        self.save_stngs = QtWidgets.QPushButton(Settings)
        self.save_stngs.setGeometry(QtCore.QRect(160, 180, 88, 27))
        self.save_stngs.setObjectName("save_stngs")
        Settings.setWindowTitle("Form")
        self.address.setText("Address:")
        self.port.setText("Port:")
        self.login.setText("Login:")
        self.password.setText("Password:")
        self.save_stngs.setText("Save")